name: Mirror to GitLab

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for mirroring history

      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/RYASTRA/nasa-mcp.git